//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiaTools.Properties {
    using System;
    
    
    /// <summary>
    ///   Classe di risorse fortemente tipizzata per la ricerca di stringhe localizzate e così via.
    /// </summary>
    // Questa classe è stata generata automaticamente dalla classe StronglyTypedResourceBuilder.
    // tramite uno strumento quale ResGen o Visual Studio.
    // Per aggiungere o rimuovere un membro, modificare il file con estensione ResX ed eseguire nuovamente ResGen
    // con l'opzione /str oppure ricompilare il progetto VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Restituisce l'istanza di ResourceManager nella cache utilizzata da questa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TiaTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Esegue l'override della proprietà CurrentUICulture del thread corrente per tutte le
        ///   ricerche di risorse eseguite utilizzando questa classe di risorse fortemente tipizzata.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA_BLOCK &quot;DB_SM&quot;
        ///{ S7_Optimized_Access := &apos;FALSE&apos; }
        ///VERSION : 0.1
        ///NON_RETAIN
        ///   STRUCT 
        ///      Sm : Array[0..$SM_NB$] of &quot;Sm_GEN&quot;;
        ///   END_STRUCT;
        ///
        ///BEGIN
        ///
        ///END_DATA_BLOCK.
        /// </summary>
        internal static string DB_SM {
            get {
                return ResourceManager.GetString("DB_SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a DATA_BLOCK &quot;DB_SM&quot;
        ///{ S7_Optimized_Access := &apos;FALSE&apos; }
        ///VERSION : 0.1
        ///NON_RETAIN
        ///   STRUCT 
        ///      Sm : Array[0..$SM_NB$] of &quot;Sm_GEN&quot;;
        ///   END_STRUCT;
        ///
        ///BEGIN
        ///
        ///END_DATA_BLOCK.
        /// </summary>
        internal static string DB_SM1 {
            get {
                return ResourceManager.GetString("DB_SM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_$SM_NB$&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_TEMP 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_$SM_NB$
        ///	//Version: x.x
        ///	//Description: State Machine $SMNb$ ($SM_NAME$)
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//Init Variables
        ///	//********************************************************************//
        ///	#SMN := 1;
        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM {
            get {
                return ResourceManager.GetString("FC_SM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Call&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Call                                     
        ///	//Version: 0.1
        ///	//Description: StateMachine Call
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///
        ///
        ///.
        /// </summary>
        internal static string FC_SM_Call {
            get {
                return ResourceManager.GetString("FC_SM_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Common&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Common
        ///	//Version: x.x
        ///	//Description: FC_SM_Common
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	//SM Status
        ///	//********************************************************************//
        ///	&quot;DB_SM&quot;.Sm[#SMN].Status.Status := 0;
        /// [stringa troncata]&quot;;.
        /// </summary>
        internal static string FC_SM_Common {
            get {
                return ResourceManager.GetString("FC_SM_Common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Pause_Seq&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Pause_Seq
        ///	//Version: x.x
        ///	//Description: FC_SM_Pause_Seq
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	CASE #SMN OF
        ///
        ///.
        /// </summary>
        internal static string FC_SM_Pause_Seq {
            get {
                return ResourceManager.GetString("FC_SM_Pause_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Reset_Seq&quot; : Void
        ///{ S7_Optimized_Access := &apos;FALSE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Reset_Seq
        ///	//Version: x.x
        ///	//Description: FC_SM_Reset_Seq
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	CASE #SMN OF
        ///
        ///
        ///.
        /// </summary>
        internal static string FC_SM_Reset_Seq {
            get {
                return ResourceManager.GetString("FC_SM_Reset_Seq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cerca una stringa localizzata simile a FUNCTION &quot;FC_SM_Stop_Seq&quot; : Void
        ///{ S7_Optimized_Access := &apos;TRUE&apos; }
        ///VERSION : 0.1
        ///   VAR_INPUT 
        ///      SMN : Int;
        ///   END_VAR
        ///
        ///
        ///BEGIN
        ///	//********************************************************************//
        ///	//Name: FC_SM_Stop_Seq
        ///	//Version: x.x
        ///	//Description: FC_SM_Stop_Seq
        ///	//Developer: Topcast
        ///	//********************************************************************//
        ///	
        ///	CASE #SMN OF
        ///
        ///
        ///.
        /// </summary>
        internal static string FC_SM_Stop_Seq {
            get {
                return ResourceManager.GetString("FC_SM_Stop_Seq", resourceCulture);
            }
        }
    }
}
